### ISSUE TITLE
Force Twemoji or just use Fontconfig to force emoji?

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.discordapp.Discord#131]
Both fix the lack of coloured emoji.

Twemoji can be shipped in the flatpak and no other emoji will be used but it will be consistent with the rest of the emojis in Discord.

We can also simply force coloured emojis which will get rid of Symbola (which we want because of https://github.com/flathub/com.discordapp.Discord/issues/106) and most likely use Noto Emojis or well, whatever emoji font your system has.

There's pros and cons to each method, I have gone forward with the former because I thought it was most appropriate but I'd like to hear your opinions.

**Comment by wpehrc** [comment]
Personally I think twemoji is the right choice simply because it's what Discord uses when they replace unicode emojis with images. All of the emojis in the compose box and message bodies are replaced with images, so it makes sense to me for us to simply match that instead of relying on the generic "emoji" type, which will most likely default to Noto Color Emoji on a lot of systems I've seen so far.

**Comment by lionirdeadman** [comment]
It's been almost 2weeks, I've not seen a single complaint about this choice so I'll close it.
