### ISSUE TITLE
"Sync with computer" theme option fails to see system theme changes

### ISSUE THREAD

**Issue by atomkreuzer** [flathub/com.discordapp.Discord#184]
I have time-based automatic system light/dark theme change enabled through Zorin Appearance. Discord recognizes both light and dark themes and switches to the right one on startup, but whenever the theme change happens while Discord is open, it simply ignores it until I quit and launch the app again.

Unrelated question: why do I have access to /usr/bin/ through upload files menu?

**Comment by lionirdeadman** [comment]
Discord doesn't have code to handle the titlebar theme syncing with the application. We have a script which does this https://github.com/flathub/com.discordapp.Discord/blob/master/set-gtk-dark-theme.py and it only works at startup.

/usr/bin is the one from flatpak.

**Comment by mattwilson888** [comment]
If restarting Discord is the only way to get the theme to update, I might as well just change it manually.

**Comment by samirkushwaha** [comment]
+1 to this.

**Comment by guihkx** [comment]
This feature now works for me™ with Discord 0.70.0, on Plasma 6.1.5:

https://github.com/user-attachments/assets/3391ba8f-8991-4351-92cc-eaa900c6984c

If this still doesn't work for you, it's *likely* because:

- You're on an "old" LTS distribution (e.g. Ubuntu 20.04)
- Your desktop environment (or xdg-portal implementation) doesn't implement the appropriate interface for clients to read system theme information

In any case, it's likely not something we can fix on this package.
