### ISSUE TITLE
Unsandboxed applications RPC

### ISSUE THREAD

**Issue by mimbrero** [flathub/com.discordapp.Discord#189]
Hello.

As said in https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc), every user has to create the symbolic link for discord-ipc-0, and even execute more commands to make it permanent, with

```bash
mkdir -p ~/.config/user-tmpfiles.d
echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf
systemctl --user enable --now systemd-tmpfiles-setup.service
```

So, why not to do this automatically, when Discord is being installed? Nobody wants to do this manually, and if you are using Discord you will surely want to use this function...

**Comment by lionirdeadman** [comment]
It's not sure that the person will need unsandboxed applications using RPC.

Furthermore, I think doing symlinks would break if done from inside the sandbox and the systemctl command would require breaking the sandbox.

**Comment by InetAddress** [comment]
Maybe the sandbox is the problem. People with no knowledge about Linux download Discord through GNOME Software, and they suddenly can't drag and drop files to chats and they notice that RPC is not working. The first weird issue in their Linux experience is probably this one (my friend's, for example).

Allowing these things by default (or even removing the sandbox) is IMO a better solution (this issue is just a discussion), as advanced users will disable the filesystem expose permission or use the browser version, and considering that if they are mad with privacy they won't use Discord at all...

**Comment by InetAddress** [comment]
I mean, I would need to tell my friend to download something called Flatseal after Discord to enable the "filesystem expose" permission manually, and in Linux the RPC feature "doesn't work" :skull:

An even worse solution would be to download Discord.tar.gz from discord.com (impossible to know what to do with that) or just use the browser version. Back to Windows then.

**Comment by InetAddress** [comment]
Oh, I just realized that, if Discord by themselves distributed Discord via Flatpak, the sandbox wouldn't just be there. This would just be the same as installing the non-Flatpak version.

I'm just giving thoughts :)

**Comment by lionirdeadman** [comment]
The sandbox cannot be entirely disabled.

My defaults are meant to be secure which is why the file access is restricted. I hope to make that better when Discord updates to Electron 14 which will allow file portal access.

I can certainly understand the frustrations and I wish these things could work better with more security. Maybe I should give a bit more specific folders in the meanwhile.

**Comment by InetAddress** [comment]
I see. Then I'll be back when Discord updates to Electron 14 in 5 years XD

Yes, adding some more folders would be an useful hotfix, like Desktop/ for some distributions, Music/, Downloads/, Videos/, Images/...

**Comment by guihkx** [comment]
>So, why not to do this automatically, when Discord is being installed?

It's impossible to do that at install-time, because by design Flatpak doesn't allow us to.

In theory, the best we could do is add a permission that would allow us to run commands outside the Flatpak sandbox, but even then, we'd only be able to run `systemctl enable ...` when we launched Discord, and not when we installed it.

Not to mention that this "solution" is really intrusive, so I also vote against it.
