### ISSUE TITLE
Missing discord:/// URL scheme handler

### ISSUE THREAD

**Issue by teohhanhui** [flathub/com.discordapp.Discord#207]

**Comment by TingPing** [comment]
It uses upstreams desktop file so this should be reported there.

**Comment by hadess** [comment]
I ran into this today, still a problem.

> It uses upstreams desktop file so this should be reported there.

Where's the upstream bug tracker so it can be reported?

Otherwise, this doesn't seem like something that couldn't be applied to the Flatpak itself, there are already changes to the desktop file in the manifest:
https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json#L63

**Comment by hadess** [comment]
Done that in the PR above.
