### ISSUE TITLE
DBus error: [6 zypak-helper] Failed to connect to session bus

### ISSUE THREAD

**Issue by pwhite1989** [flathub/com.discordapp.Discord#213]
Hello, I get the following error when I run `flatpak run com.discordapp.Discord` on a brand new install of Void Linux:

```shell
settings.json doesn't yet exist, can't disable it yet
[6 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[6 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus
/app/bin/discord: line 18:     6 Aborted                 env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
```

Followed by:

````shell
Error opening settings.json: [Errno 2] No such file or directory: '/home/user/.var/app/com.discordapp.Discord/config/discord/settings.json'
```

**Comment by TingPing** [comment]
Based on the error you just don't have a valid dbus session on the host?

**Comment by rebeltaz** [comment]
I know that this is old, but for future reference, for anyone else who has this issue, the problem is related to flatpak's sandboxing. You need to install FlatSeal 

`flatpak install flatseal`

then, run FlatSeal with

`flatpak run com.github.tchx84.Flatseal`

Under 'Applications', navigate to 'Discord'. On the right hand side, scroll down to 'Socket'. Under that, you will see a setting for 'D-Bus session bus'. You need to toggle that to 'Enabled/On'. 

Once you do that, you can then run discord using `flatpak run com.discordapp.Discord` with no trouble.

**Comment by rebeltaz** [comment]
> That is very much the incorrect solution, just disabling sandboxing basically. Flatpak already creates a session bus inside the sandbox that is filtered.

Well, it's the only way I could get it to work and I didn't see any better/other solutions... 🤷‍♂️
