### ISSUE TITLE
Discord is just a blank screen

### ISSUE THREAD

**Issue by Elijahrane** [flathub/com.discordapp.Discord#227]
OS: Fedora 36
GPU: AMD Radeon RX 5500 XT (Default drivers)
GNOME version: 42.2
Kernel version: 5.18.5-200.fc36.x86_64

Doesn't work in either wayland or xorg.
This is what discord looks like when I launch it (screenshot taken in wayland)
![image](https://user-images.githubusercontent.com/60792108/174808638-23d35350-fad1-4132-b20e-f4f587c8670d.png)

System is fully updated. I don't have much software installed beyond what comes with default Fedora GNOME
![image](https://user-images.githubusercontent.com/60792108/174809727-35600108-b92d-44ba-954c-327e3ae64041.png)

```
$ flatpak run com.discordapp.Discord
2022/06/21 09:15:43 socat[3] E "/run/user/1000/app/com.discordapp.Discord/discord-ipc-0" exists
Disabling updates already done
Discord 0.0.18
Quitting secondary instance.
Gtk-Message: 09:15:44.268: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:15:44.269: Failed to load module "pk-gtk-module"
Gtk-Message: 09:15:44.269: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:15:44.269: Failed to load module "pk-gtk-module"
/app/bin/discord: line 19: kill: (3) - No such process
```

**Comment by TingPing** [comment]
See this comment: https://github.com/flathub/com.discordapp.Discord/issues/210#issuecomment-1097048198

**Comment by b-m-f** [comment]
same problem here

**Comment by jdandrea** [comment]
Seeing the same symptoms here:

OS: Fedora 36 (fresh/new install)
GPU: NVIDIA Corporation GM204 [GeForce GTX 980]
GNOME version: 42.3 (Wayland)
Kernel version: 5.18.13-200.fc36.x86_64

Eventually seems to get stuck here:

```
[2022-07-24 18:11:33.274] [172] (device_info_linux.cc:45): NumberOfDevices
[2022-07-24 18:11:33.372] [172] (device_info_linux.cc:45): NumberOfDevices
[2022-07-24 18:11:33.373] [172] (device_info_linux.cc:78): GetDeviceName
[2022-07-24 18:11:36.375] [172] (device_info_linux.cc:45): NumberOfDevices
[2022-07-24 18:11:36.472] [172] (device_info_linux.cc:45): NumberOfDevices
[2022-07-24 18:11:36.472] [172] (device_info_linux.cc:78): GetDeviceName
```

... then it handles an `OnDevicesChanged` (but I didn't change anything)... and eventually lands back at the above again, and round and round it goes.

**Comment by TingPing** [comment]
Maybe we could add `--disable-gpu` if you use NVidia+XWayland. (I'd just recommend you avoid that combination for a while, its still quite broken IME.)

**Comment by paulimer** [comment]
Hi ! I don't have this issue (blank screen), however I do have the journalctl looping logs same as @jdandrea. However, I do not have a Nvidia gpu :

OS: Fedora 36 
GPU: Mesa Intel® HD Graphics 530 (SKL GT2)
GNOME version: 42.3 (Wayland)
Kernel version: 5.18.13-200.fc36.x86_64

I came across this in the journal looking for a waking from sleep bug, blocking the whole GNOME shell after password validation. 

In any case, the blank screen issue is probably not caused by this.

**Comment by XaurDesu** [comment]
Currently using Nvidia GTX 960 + Fedora 37 + Wayland in a GNOME desktop environment, i seem to have this problem in GNOME, but when i switch to KDE + Wayland it dissapears. Not sure what to make of it.

**Comment by merryhime** [comment]
This is occurring for myself on a GTX 4070 + Fedora 38 + Wayland in a GNOME desktop environment.

**Comment by guihkx** [comment]
Can someone please retest this with latest Discord (0.0.70) and runtime (24.08)?

Thank you.

**Comment by guihkx** [comment]
Closing, since nobody seems available to retest this with the current Discord version.

If the problem still persists, I'd suggest you [report it to Discord devs](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug), or [simply opt-out of Wayland support](https://github.com/flathub/com.discordapp.Discord?tab=readme-ov-file#wayland) until it improves with time.
