### ISSUE TITLE
"TypeError: coreModule.startup is not a function" | Steam Deck

### ISSUE THREAD

**Issue by derrickjon** [flathub/com.discordapp.Discord#229]
When I install the flatpak on my Steam Deck and attempt to launch the app I immediately get this error "A fatal Javascript error occured"

"TypeError: coreModule.startup is not a function"

Any ideas on how to work around this on the Steam Deck? Seems most people are able to use it without any issues. I am not super familiar with trouble shooting things like this in Linux.

![IMG-4338](https://user-images.githubusercontent.com/59344513/176221009-e9e3b39a-d2d0-4d36-9f7d-6b8cf5707a88.jpg)

**Comment by ntippie** [comment]
Fixed for me with `flatpak remove com.discordapp.Discord --delete-data` and then reinstall.

**Comment by guihkx** [comment]
That's the same error message as reported in #271, meaning that this issue is not exclusive to the Flatpak package.

My usual recommendation is to report these issues, with as much detail as possible, to the [appropriate channel](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.

Thanks for understanding.
