### ISSUE TITLE
Could not connect to discord via RPC:Error:Could not Connect

### ISSUE THREAD

**Issue by Debin12** [flathub/com.discordapp.Discord#241]

**Comment by AlchlcDvl** [comment]
I am also having the same error, here is a screenshot
![image](https://user-images.githubusercontent.com/56699741/194037054-58d455c9-e968-4323-8b20-1ef82d4a7b65.png)

**Comment by TeemoCell** [comment]
I have the same problem.

**Comment by ZloyMolodoy** [comment]
> I am also having the same error, here is a screenshot ![image](https://user-images.githubusercontent.com/56699741/194037054-58d455c9-e968-4323-8b20-1ef82d4a7b65.png)

Try not to run discord as administrator

**Comment by linus-ha** [comment]
https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by Neutrovertido** [comment]
the wiki solution doesn't work either, with none of my rich presence apps

**Comment by zastrixarundell** [comment]
+1 on this issue https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc) doesn't seem to help me. 
![image](https://user-images.githubusercontent.com/30195425/201280838-6ed4a680-d219-4c9b-908a-80c67ebb5956.png)

**Comment by kira-pareser** [comment]
You may try 
Goes to Visual Code -> Ctrl + P 
type ">discord.reconnect" or ">discord.disable" then ">discord.enable"

or reinstall extension

**Comment by sageyx2002** [comment]
Happens on and off. Not sure what causes is, my own RPC client connects fine, so does another extension if I try it instead

Here is the runtime status log:
```
Activation Event: Startup
Activation Time: 6ms

Uncaught Errors (5)
Cannot read properties of null (reading 'write')
Cannot read properties of null (reading 'write')
Cannot read properties of null (reading 'write')
Cannot read properties of null (reading 'write')
Cannot read properties of null (reading 'write')
```
The above is a result of pressing the reconnect button, with a reconnect triggering 2 new null reads, the startup triggering one. There appears to be an internal reference error, this may be worth investigating on. I'd also recommend rate limiting the reconnect action to once every x seconds, in order to avoid spam

![image](https://github.com/flathub/com.discordapp.Discord/assets/104058571/18442248-b756-4ed8-af0b-c28eac8022aa)

Error message:
```
Couldn't connect to Discord via RPC: Error: Could not connect
```

**Comment by NotNullBool** [comment]
For me it works if I hard link the rpc instead of symbolic link
