### ISSUE TITLE
Electron 22 updates

### ISSUE THREAD

**Issue by JavkhlanK** [flathub/com.discordapp.Discord#305]
~~Looks like Electron 22 is finally used in stable too and that includes it using the xdg-desktop-portal file picker automatically. Can `--filesystem=xdg-videos:ro`, `--filesystem=xdg-pictures:ro`, and `--filesystem=xdg-download` be dropped?~~ I overlooked #280, sorry.

And what about allowing Wayland by default?

**Comment by kaimast** [comment]
Would be great if Wayland could be enabled by default! The slack flathub package did this and it seems to work fine for me.

**Comment by guihkx** [comment]
In my understanding, Wayland support was not enabled by default by past collaborators due to Wayland-specific issues (for example: #89, #291, #413)

Though I admittedly don't know if that's still the case today (I don't/can't use Wayland to verify), I also think it's really easy to manually [enable Wayland by default](https://github.com/flathub/com.discordapp.Discord?tab=readme-ov-file#wayland).

We can always revisit this topic in the future, of course.
