### ISSUE TITLE
"Discord installation is corrupt" and stuck on RTC Connecting

### ISSUE THREAD

**Issue by ghost** [flathub/com.discordapp.Discord#310]
I installed Discord today on my openSUSE Aeon (formerly MicroOS Desktop) install and I was greeted with this red banner above the app. No matter what I did, like deleting the folder from .var/app or updating my host system, nothing works. I cannot connect to any voice chat and at times when I launch the app, I get logged out and have to re-enter my credentials.
It also seems like it has trouble recognizing my Input and Output devices, but it does play notification sounds.

![Screenshot from 2023-07-15 14-42-18-obfuscated](https://github.com/flathub/com.discordapp.Discord/assets/78095397/f5925353-1a87-4b7a-b89b-773b441610b1)
![Screenshot from 2023-07-15 14-39-45-obfuscated](https://github.com/flathub/com.discordapp.Discord/assets/78095397/7047c44f-40db-4576-bb79-ebb38a19d4e5)

**Comment by JoshTrono** [comment]
I am also having this issue. A fresh install of Opensuse aeon (MicroOs). Running it from the command line gives this multiple times
```
[5:0716/202616.554434:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
I tried all the workaround (that I found) with dbus but nothing seem to be working on Opensuse Aeon

**Comment by JoshTrono** [comment]
I got discord to work on my side. Had to reinstall openSuse Aeon/MicroOs through the tumbleweed installer and selecting transactional server then add microOs gnome desktop inside the software section. Once I booted it up I was able to install discord flatpak and run it. All I had to do was manually install distrobox.

This seems like OpenSuse microOs installer issue not a flatpak issue and since it's still in RC I tried the Tumbleweed installer

**Comment by DarielVR** [comment]
This happens because of [SELinux policies on Aeon/Kalpa](https://en.opensuse.org/Portal:Aeon#Steam_Proton,_Bottles,_WINE,_Lutris,_Android_Studio_emulator_not_working_from_flatpaks). If you do `ausearch -m AVC,USER_AVC,SELINUX_ERR,USER_SELINUX_ERR | grep Discord` with sudo, you will get an output like this `type=AVC msg=audit(1689654119.769:130): avc:  denied  { execstack } for  pid=4319 comm="Discord" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0`. 
So executing `setsebool selinuxuser_execstack 1` with sudo fixes the problem. However, this is considered insecure and the default policy won't be changed; in theory, it can be fixed on the application side, but I'm not sure if something can be done for the discord flatpak and doing a rollback to a previous snapshot doesn't seem to fix the problem.

**Comment by grisu48** [comment]
I filed https://bugzilla.opensuse.org/show_bug.cgi?id=1216237 for this.

**Comment by guihkx** [comment]
Looks like this is not our bug. Closing.
