### ISSUE TITLE
Fcitx/Mozc fail to enter text into Discord's input boxes

### ISSUE THREAD

**Issue by Dormanil** [flathub/com.discordapp.Discord#33]
Another one of those issues that I suspect have to deal with the sandbox, but Mozc refuses to send the finished text over to the input box.
![screenshot_20180620_211010](https://user-images.githubusercontent.com/6816490/41657454-61ae9320-74ce-11e8-9f43-5d12ea784a3a.png)
Whenever I hit enter to select the current suggestion, it closes the Mozc suggestion widget and (unlike usual) does not enter the finished text into the input box.

**Comment by tagoh** [comment]
Discord on flatpak doesn't work with even ibus. apparently GTK_IM_MODULE isn't simply exported. so "flatpak run --env=GTK_IM_MODULE=ibus com.discordapp.Discord resolves this problem for me.

**Comment by tagoh** [comment]
That should be a workaround. the root cause is probably Discord app doesn't recognize gnome-settings-daemon or dconf session. that environment variable should be basically set by gnome-settings-daemon through XSETTINGS or the key org.gnome.desktop.interface.gtk-im-module in dconf. in fact ibus works fine on gedit flatpak app but they don't set this environment variable but have some for dconf in their manifest.

**Comment by libertylocked** [comment]
If you use fcitx you can run discord with `GTK_IM_MODULE=xim`
(Also works for any other flatpaks)
So you can run
```
GTK_IM_MODULE=xim flatpak run com.discordapp.Discord
```
