### ISSUE TITLE
Missing Discord icon in window titlebar 

### ISSUE THREAD

**Issue by grz0** [flathub/com.discordapp.Discord#348]
Environment:
KDE 5.27.9
Fedora 39

![image](https://github.com/flathub/com.discordapp.Discord/assets/3605541/8e79895a-c76a-4633-9845-8a68f261e490)

**Comment by TingPing** [comment]
This is a KDE thing. They get the icon from the desktop file.

However I have no idea how to tell KDE what the desktop file is, their docs only talk about Qt: https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

**Comment by Vilianexe** [comment]
there is a work around, press alt-f->more actions->special window settings->add property->.desktop file name and put com.discordapp.Discord there

**Comment by Vilianexe** [comment]
> This is a KDE thing. They get the icon from the desktop file.
> 
> However I have no idea how to tell KDE what the desktop file is, their docs only talk about Qt: https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

i usually see people fixing this renaming the application executable to match the icon
![image](https://github.com/flathub/com.discordapp.Discord/assets/72302817/6d3bc4ed-7805-4f70-85cf-30b0bea73d8e)
apparently kde read the executable and try to find and icon with the name, but fails because the icon is name "com.discordapp.Discord"

https://bugzilla.mozilla.org/show_bug.cgi?id=1782448 firefox had the same bug
