### ISSUE TITLE
PERF: Since last commit discord screensharing is slow

### ISSUE THREAD

**Issue by Vixea** [flathub/com.discordapp.Discord#366]
I hope that satisfies your testing

**Comment by TingPing** [comment]
We're kinda stuck in a bad place.

Upstream Chromium/Electron don't enable these features because they deem them unstable.

When enabling them some users confirm they don't work.

So we need to somehow narrow down what doesn't and doesn't work with which features...

And on top of all of that Discord is likely behind on Electron updates for fixes.

**Comment by Vixea** [comment]
Any updates now that chromium is all caught up?

**Comment by guihkx** [comment]
Is this still an issue for you? The latest Discord update (0.0.70) now includes Electron 32, which is the newest stable version they offer.

Also, can you please provide a bit more detail on this? Like your distro, GPU model, GPU driver version, Wayland or X11, desktop environment...

It's also difficult to know what you mean by "slow" since we don't really have a reference for "not slow".

**Comment by guihkx** [comment]
Closing, as the reporter does not seem available for a follow-up at this time. 

Though, even if he was, I find it unlikely that there's something we could do to improve Discord's screen sharing performance.

I suggest that people report alike issues [to Discord devs](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.

**Comment by Vixea** [comment]
Fine by me, I'm not currently using the flatpak version
