### ISSUE TITLE
File uploading doesn't work.

### ISSUE THREAD

**Issue by Il-Jovan** [flathub/com.discordapp.Discord#396]
When uploading a file on the flatpak version of discord, it doesn't open any menu making it harder to upload an image file without copying it and pasting onto the chat.
It'd be great to fix this bug.

**Comment by guihkx** [comment]
Is this still an issue for you with the latest Discord update?

I'm also a bit confused about the issue itself... Does the plus ("+") button to upload a file not do anything when you click it?

**Comment by guihkx** [comment]
Closing, as the reporter does not seem available for a follow-up at this time.

Please retest this with latest Discord, and open a new issue if the problem still persists.

Please also note that dragging and dropping files onto Discord still doesn't work (except when those files come from the following folders: `~/Videos`, `~/Pictures` or `~/Downloads`), and that's an issue that can only be fixed by Electron: 

- https://github.com/electron/electron/issues/30650
