### ISSUE TITLE
flathubbot going in circles with 0.0.68?

### ISSUE THREAD

**Issue by mvdan** [flathub/com.discordapp.Discord#437]
It keeps doing dummy updates from 0.0.68 to 0.0.68, going back and forth between two URLs which presumably lead to the same release archive: https://github.com/flathub/com.discordapp.Discord/pulls?q=is%3Apr+0.0.68

**Comment by mvdan** [comment]
cc @lionirdeadman

**Comment by guihkx** [comment]
See also: https://github.com/flathub-infra/flatpak-external-data-checker/issues/438

I think the best option right now is to disable Flathub's update-checker.

However, my impression is that this package is barely maintained (even though it's "official"), so future client updates might get delayed.

**Comment by guihkx** [comment]
Please note that even though this issue is closed, the [underlying issue](https://github.com/flathub-infra/flatpak-external-data-checker/issues/438) still exists.

For now though, all Discord updates will be pushed manually by me (but still checked automatically [[1]](https://github.com/guihkx/nvchecker/commit/1714568a0d6617ad5800da65bac45b072df3d8fd) [[2]](https://github.com/guihkx/nvchecker/actions/workflows/nvchecker.yml), for faster updates).
