### ISSUE TITLE
Unread Notification Counter On Taskbar Icon

### ISSUE THREAD

**Issue by Retro8bit** [flathub/com.discordapp.Discord#450]
Since the latest update to the Flatpak (version 0.0.70) I am now getting an unread notification badge/counter on the app icon in my taskbar with no way to turn it off within Discord (to my knowledge). 
![image](https://github.com/user-attachments/assets/c7f237c6-f247-4d5a-871a-4aff556e6470)

Toggling the "Enable Unread Message Badge" setting in the Notifications settings page only shows/hides the red dot on the Discord system tray icon and has no impact on the taskbar icon. 

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Graphics Platform: Wayland

**Comment by Retro8bit** [comment]
Figured it out. You can disable taskbar notification badges globally in KDE via the Settings app under "Apps & Windows -> Notifications -> Additional feedback -> Notification badges" and then you can uncheck the "Show in task manager" box to disable them.

This does disable them system-wide though, so it would still be nice to be able to customize this behaviour within Discord incase you have other apps you want to actually see taskbar notifications. That will probably need to be an upstream change though.

**Comment by guihkx** [comment]
Weird, I have unread private messages on Discord, but I don't see the unread badge counter here (I'm on the same Plasma version as you, except that I'm on X11, which shouldn't matter, I think).

But thanks for documenting how to disable that feature anyway, I'm sure it'll be helpful for some people.

However, since this is not an issue specific to the Flatpak package, I recommend you to report it [upstream](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.

**Comment by Retro8bit** [comment]
Reported upstream, thanks for pointing me in their direction.
