### ISSUE TITLE
Error: Update is older than current version

### ISSUE THREAD

**Issue by WendelVolm** [flathub/com.discordapp.Discord#461]
`flatpak update`

```
        ID                              Branch          Op          Remote          Download
 1. [✗] com.discordapp.Discord          stable          u           flathub         1,0 kB / 112,9 MB

Error: While pulling app/com.discordapp.Discord/x86_64/stable from remote flathub: Update is older than current version
Updates complete.
error: There were one or more errors
```

**Comment by guihkx** [comment]
No idea why or how that happens,but it's probably temporary...

Can you please share the output of `flatpak info com.discordapp.Discord//stable`?

**Comment by guihkx** [comment]
Ah, I see what happened...

Because I've been pushing frequent changes to this package, Flathub somehow published these changes in an unsynchronized manner.

We can verify this by comparing the order of commits from `flatpak remote-info --log flathub com.discordapp.Discord` with the real order of commits [made here on GitHub](https://github.com/flathub/com.discordapp.Discord/commits/master/).

I'm not sure why Flathub did that, but I don't think it's my fault. lol

In any case, [the most recent build](https://buildbot.flathub.org/#/builders/6/builds/151855) is yet to be published (in less than an hour, perhaps), so once that's done, you should be able to run `flatpak update` without issues.

If that doesn't happen, feel free to reopen this.
