### ISSUE TITLE
Cannot access to Documents folder to upload files nor upload files directly from drag and drop from Documents

### ISSUE THREAD

**Issue by amuhz** [flathub/com.discordapp.Discord#480]
## Description
I can't access to the path /home/username/Documents when I need to upload a file from my filesystem to Discord.
It was perfectly fine yesterday and broke after updating Discord this morning.

## System and Versions
Linux distro : Mageia 9
Discord version : 0.0.75 with Flatpak

## Steps to reproduce the issue
Do either :
1. Open Discord.
2. Go to any server text channel, group message or direct message.
3. Select "Upload a File".
**--> No "Documents" folder will be shown in the window opened.**
![Screenshot_20241119_144215](https://github.com/user-attachments/assets/a0f10a96-f087-4a1f-bf91-225a58643818)

Or :
1. Open Discord.
2. Open your file manager.
3. Drag and drop a file from any /home/username/Documents subfolders into Discord.
5. Try to send the file.
**--> An error message should be shown**
![Screenshot_20241119_144716(2)](https://github.com/user-attachments/assets/d5d0b8c0-9215-465c-8d7d-7747c6d51f2f)

**Comment by Jack-Balcombe** [comment]
I had the exact same issue just now. Discord can only see three folders in my home directory.

Linux Distro: Linux Mint 22 Cinnamon
Discord Version: Flatpak 0.0.75

![ksnip_20241120-024342](https://github.com/user-attachments/assets/9f68ebc5-a4fd-467f-abf0-5c5d52b1cf8b)

The issue seems to be specific to the Flatpak version of Discord, because I tried uploading files to the web version and it works without any issues.

It also seems to affect downloading files. If I try saving images from Discord to any folder other than the ones it can see, the file is not saved (although Discord appears to believe it has been saved).

**Comment by Jack-Balcombe** [comment]
@amuhz are you using Cinnamon and/or the Nemo file manager?
